# Generated by Django 3.2.5 on 2021-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics'),
        ),
    ]
